### PR TITLE
Refactor bus-mapping

### LINKED ISSUE #127: Extend bus-mapping to work by blocks instead of by txs
Currently the bus-mapping is designed to parse and output a witness for a single tx, but we will be working by blocks which contain a list of txs.
- The GlobalCounter should be kept for the entire block (instead of starting at 0 at each tx)
- Each tx starts in a different context, which we sometimes need to store in the execution_steps.  We can introduce a `CallContext` that is initialized from the tx data at the beginning of the trace, that also keeps track of further `CALL`, `STATICALL`, and `DELEGATEDCALL`.

### LINKED ISSUE #139: Implement GethExecTrace and GethExecStep for Trace generation ergonomics
As suggested by @ed255, the current process of generating an `ExecutionTrace` is not the best since we need to do two iterations. The first parses and leaves some fields initialized to zero and the second actually puts the correct values.

Instead, it would be nice to have two internal structures used to do this process, which are not visible/exported to the user and then, only convert them to `ExecutionTrace` and `ExecutionStep` when we perform this "second iteration".

### LINKED ISSUE #151: Try to use types from web3 crate instead of custom ones
See https://docs.rs/web3/0.17.0/web3/types/index.html
We can use:
- Address
- U256 for EvmWord
- Transaction, Block

### LINKED ISSUE #152: Introduce a CircuitInputsBuilder
The CircuitInputBuildes generates all the inputs, including the bus mapping part.  This CircuitInputBuilder would be fed with RPC responses from geth, it will also be connected to a partial MPT (for example, built in go), and it would generate everything from there to feed to prover.

Example of how it could look like:

```rust

#[derive(Debug)]
pub struct Block<F: FieldExt> {
    constants: BlockConstants<F>,
    ctx: BlockContext,
    txs: Vec<Transaction>,
}

impl<F: FieldExt> Block<F> {
    pub fn new(geth_block: &GethBlock, constants: BlockConstants<F>) -> Self {
        Self {
            constants,
            ctx: BlockContext::new(),
            txs: Vec::new(),
        }
    }
}

#[derive(Debug)]
pub struct Transaction {
    ctx: TransactionContext,
    steps: Vec<ExecutionStep>,
}

impl Transaction {
    pub fn new(geth_tx: &GethTransaction) -> Self {
        Self {
            ctx: TransactionContext::new(geth_tx),
            steps: Vec::new(),
        }
    }
}

#[derive(Debug)]
pub struct TransactionContext {
    address: Address,
}

impl TransactionContext {
    pub fn new(tx: &GethTransaction) -> Self {
        Self {
            address: Address::from([0; 20]),
        }
    }
}

#[derive(Debug)]
pub struct BlockContext {
    gc: GlobalCounter,
    container: OperationContainer,
}

impl BlockContext {
    pub fn new() -> Self {
        Self {
            gc: GlobalCounter::new(),
            container: OperationContainer::new(),
        }
    }
}

pub struct Context<'a> {
    block: &'a BlockContext,
    tx: &'a TransactionContext,
}

#[derive(Debug)]
pub struct CircuitInputBuilder<F: FieldExt + Debug> {
    block: Block<F>,
}

impl<F: FieldExt> CircuitInputBuilder<F> {
    pub fn new(geth_block: GethBlock, constants: BlockConstants<F>) -> Self {
        Self {
            block: Block::new(&geth_block, constants),
        }
    }

    pub fn handle_tx(
        &mut self,
        geth_tx: &GethTransaction,
        geth_trace: &GethExecTrace,
    ) -> Result<(), Error> {
        let mut tx = Transaction::new(&geth_tx);
        let mut ctx = Context {
            block: &self.block.ctx,
            tx: &tx.ctx,
        };
        for (index, geth_step) in geth_trace.struct_logs.iter().enumerate() {
            let mut step = ExecutionStep::new(&geth_step, self.block.ctx.gc);
            step.gen_associated_ops(
                &mut ctx,
                &geth_trace.struct_logs[index..],
            )?;
            tx.steps.push(step);
        }
        self.block.txs.push(tx);
        Ok(())
    }
}
```

### PR DESCRIPTION
**Pull request by ed255**
- Introduce the CircuitInputBuilder, which allows building the circuit
  inputs by taking types returned by geth and parsing them to generate
  the appropiate outputs.  The CircuitInputBuilder works by firs taking
  a block and then transactions and their associated execution traces.
  - The CircuitInputBuilder works by steps:
    1. Take a block
    2. Take each tx in the block
    3. Take each exec trace in the tx
  - The CircuitInpubBuilder in general is designed with 3 concepts that
    apply to 3 levels (block, tx, exec step):
    a. Input data: types obtained from geth (or in the future other
    modules like the partial merkle tree).
    b. context: data that must be available from one step to the other.
    c. Output data: data generated from Input data + context, that forms
    the circuit inputs.
- Previously there was a single type for ExecutionStep used both for
  deserializing and for circuit input.  Now the types are split into
  eth_types (which contains all types that geth / web3 can return), and
  internal structs in the CircuitInputBuilder which only contain the
  inputs required by the circuit.
- Introduce the eth_types modules (mentioned before).  Some of the types
  are reexported from rust-web3, others not available in external crates
  are defined.
- Introduce helper macros useful for tests to declare Address, Word and
  Word->Word maps from hex strings.
- Introduce mock data generators for tests.
- Rename `EvmWord` to `Word`.
- Rename `ExecutionTrace` to `ExecTrace`.
- Rename `ExecutionStep` to `ExecStep`.

Resolve #152
Resolve #151
Resolve #139
Resolve #127

### CODE REVIEW

File: bus-mapping/src/circuit_input_builder.rs [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+            tx.steps.push(step);
+        }
+        self.block.txs.push(tx);
+        Ok(())
+    }
+}
+
+use crate::bytecode::Bytecode;
+use crate::evm::Gas;
+use crate::external_tracer;
```
Comment (CPerezz) [inline bus-mapping/src/circuit_input_builder.rs:224]: Can we move this to the top of the file?

File: bus-mapping/src/circuit_input_builder.rs [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+
+/// MockBlock is a type that contains all the information from a block required to build the
+/// circuit inputs.
+pub struct MockBlock {
+    pub eth_block: eth_types::Block<()>,
+    pub eth_tx: eth_types::Transaction,
+    pub block_ctants: BlockConstants,
+    pub geth_trace: eth_types::GethExecTrace,
+}
```
Comment (CPerezz) [inline bus-mapping/src/circuit_input_builder.rs:233]: If this is only going to be used for thesting, I would probably add it in a sepparated module under a #[cfg(test)] feature.

On that way it's less confusing.

File: bus-mapping/src/eth_types.rs [hunk 3]
```diff
@@ -0,0 +1,485 @@
...
+pub trait ToWord {
+    /// Convert the type to a [`Word`].
+    fn to_word(&self) -> Word;
+}
+
+/// Trait uset do convert a scalar value to a 32 byte array in big endian.
+pub trait ToBigEndian {
+    /// Convert the value to a 32 byte array in big endian.
+    fn to_be_bytes(&self) -> [u8; 32];
+}
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:29]: Should we also add one for `LittleEndian`? For consistency I mean.

File: bus-mapping/src/eth_types.rs [hunk 4]
```diff
@@ -0,0 +1,485 @@
...
+        if s == "0x00" {
+            serializer.serialize_str("0x0")
+        } else {
+            serializer.serialize_str(&s)
+        }
+    }
+}
+
+impl<F: FieldExt> ToScalar<F> for DebugU256 {
+    fn to_scalar(&self) -> CtOption<F> {
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:68]: As we discussed `CtOption` API is not the best one to have. Specially if we're not developing anything that needs to be ctant time.

I would talk to @miha-stopar and @han0110 and consider returning and using `Option`.

`CtOption` contains an Into conversion to it, so should be trivial to adapt it, and would give us much more flexibility.
I made that PR IIRC: https://github.com/dalek-cryptography/subtle/pull/75

File: bus-mapping/src/eth_types.rs [hunk 5]
```diff
@@ -0,0 +1,485 @@
...
+    /// Encode the value as byte array in big endian.
+    fn to_be_bytes(&self) -> [u8; 32] {
+        let mut bytes = [0u8; 32];
+        self.to_big_endian(&mut bytes);
+        bytes
+    }
+}
+
+impl<F: FieldExt> ToScalar<F> for U256 {
+    fn to_scalar(&self) -> CtOption<F> {
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:103]: ditto

File: bus-mapping/src/eth_types.rs [hunk 6]
```diff
@@ -0,0 +1,485 @@
...
+
+impl<F: FieldExt> ToScalar<F> for Address {
+    fn to_scalar(&self) -> CtOption<F> {
+        let mut bytes = [0u8; 32];
+        bytes[32 - Self::len_bytes()..].copy_from_slice(self.as_bytes());
+        F::from_bytes(&bytes)
+    }
+}
+
+pub use types::Block;
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:132]: Move to the top of the file

File: bus-mapping/src/eth_types.rs [hunk 7]
```diff
@@ -0,0 +1,485 @@
...
+
+/// Generate a new mock block with preloaded data, useful for tests.
+pub fn new_block_mock() -> Block<()> {
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:135]: I would add this as cfg test too IMO.

File: bus-mapping/src/eth_types.rs [hunk 8]
```diff
@@ -0,0 +1,485 @@
...
+        seal_fields: Vec::new(),
+        uncles: Vec::new(),
+        transactions: Vec::new(),
+        size: None,
+        mix_hash: None,
+        nonce: Some(H64([0u8; 8])),
+    }
+}
+
+pub use types::Transaction;
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:162]: ditto

File: bus-mapping/src/eth_types.rs [hunk 9]
```diff
@@ -0,0 +1,485 @@
...
+
+/// Generate a new mock transaction with preloaded data, useful for tests.
+pub fn new_tx_mock<TX>(block: &Block<TX>) -> Transaction {
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:165]: ditto.

File: bus-mapping/src/eth_types.rs [hunk 10]
```diff
@@ -0,0 +1,485 @@
...
+#[doc(hidden)]
+pub struct GethExecTrace {
+    pub gas: Gas,
+    pub failed: bool,
+    // return_value is a hex encoded byte array
+    #[serde(alias = "structLogs")]
+    pub struct_logs: Vec<GethExecStep>,
+}
+
+// TODO: Move this test macros to a crate, export them, and use them in all tests
```
Comment (CPerezz) [inline bus-mapping/src/eth_types.rs:270]: Can we file an issue and remove the TODO? On that way we will not forget about it :)

File: bus-mapping/src/evm.rs [hunk 11]
```diff
@@ -93,6 +90,8 @@ impl GlobalCounter {
     }
 }
 
+/*
+<<<<<<< HEAD
```
Comment (CPerezz) [inline bus-mapping/src/evm.rs:94]: Rebasing leftovers to be removed.

File: bus-mapping/src/evm.rs [hunk 12]
```diff
@@ -262,14 +261,20 @@ impl EthAddress {
         EvmWord(inner)
     }
 }
+=======
+*/
```
Comment (CPerezz) [inline bus-mapping/src/evm.rs:265]: ditto

File: bus-mapping/src/evm.rs [hunk 13]
```diff
@@ -323,6 +328,8 @@ impl From<u64> for GasCost {
         GasCost(cost)
     }
 }
+/*
+<<<<<<< HEAD
```
Comment (CPerezz) [inline bus-mapping/src/evm.rs:332]: ditto.

File: bus-mapping/src/evm.rs [hunk 14]
```diff
@@ -417,3 +424,6 @@ mod evm_tests {
         );
     }
 }
+=======
+>>>>>>> 9d7f263 (Refactor bus-mapping)
+*/
```
Comment (CPerezz) [inline bus-mapping/src/evm.rs:429]: ditto.

File: bus-mapping/src/evm/opcodes/add.rs [hunk 15]
```diff
@@ -115,65 +80,68 @@ mod add_tests {
...
-
-        // Generate Step1 corresponding to ADD
-        let mut step_1 = step_setup(
-            Stack(vec![stack_value_a, stack_value_b]),
-            ADD,
-            obtained_steps[0].clone(),
-            ctx.gc,
+        let mut mock = MockBlock::new_single_tx_trace_code(&code).unwrap();
+        mock.geth_trace.struct_logs =
+            mock.geth_trace.struct_logs[code.get_pos("start")..].to_vec();
```
Comment (CPerezz) [inline bus-mapping/src/evm/opcodes/add.rs:86]: Would be nice if `MockBlock` could have a fn that mixes both actions.

File: bus-mapping/src/external_tracer.rs [hunk 16]
```diff
@@ -1,78 +1,90 @@
...
+use crate::bytecode::Bytecode;
+use crate::eth_types::{self, Address, GethExecStep, Word};
+use crate::BlockConstants;
 use crate::Error;
-use crate::{
-    bytecode::Bytecode, BlockConstants, ExecutionStep, ExecutionTrace,
-};
 use geth_utils;
-use pasta_curves::arithmetic::FieldExt;
+// use pasta_curves::arithmetic::FieldExt;
```
Comment (CPerezz) [inline bus-mapping/src/external_tracer.rs:7]: Remove if unused.

File: bus-mapping/src/external_tracer.rs [hunk 17]
```diff
@@ -1,78 +1,90 @@
...
+            // TODO: Capture error into TracingError if possible
             .map_err(|_| Error::TracingError)?;
 
+    // TODO: Capture error into TracingError if possible
+    let trace: Vec<GethExecStep> =
+        serde_json::from_str(&trace_string).map_err(|_| Error::TracingError)?;
+    Ok(trace)
     // Generate the execution steps
-    ExecutionTrace::<F>::load_trace(trace.as_bytes())
+    // ExecutionTrace::load_trace(trace.as_bytes())
```
Comment (CPerezz) [inline bus-mapping/src/external_tracer.rs:89]: Remove if unused.

File: bus-mapping/src/external_tracer.rs [hunk 18]
```diff
@@ -1,78 +1,90 @@
...
-        accounts: vec![account],
+        transaction: tx.clone(),
+        accounts: accounts.to_vec(),
     };
 
     // Get the trace
-    let trace =
+    let trace_string =
         geth_utils::trace(&serde_json::to_string(&geth_config).unwrap())
+            // TODO: Capture error into TracingError if possible
```
Comment (CPerezz) [inline bus-mapping/src/external_tracer.rs:81]: I'd say we either address this in this PR or we file an issue for it and so we remove the `TODO`.

File: bus-mapping/src/external_tracer.rs [hunk 19]
```diff
@@ -1,78 +1,90 @@
...
             .map_err(|_| Error::TracingError)?;
 
+    // TODO: Capture error into TracingError if possible
```
Comment (CPerezz) [inline bus-mapping/src/external_tracer.rs:84]: ditto

**Review by CPerezz — CHANGES_REQUESTED** [review]
Awesome job @ed255 I really like the refactor of the crate and the introduction of the Web3 types!

I left some remarks, nits and would love to hear your takes on them. :smile: 

Amazing job!!!! :clap:

File: Cargo.toml [hunk 20]
```diff
@@ -8,3 +8,8 @@ members = [
 
 [patch.crates-io]
 halo2 = { git = "https://github.com/zcash/halo2.git", rev = "4283713ec76051eaf21a06d0279fa7d3497cafb6" }
+# This fork makes bitvec 0.20.x work with funty 1.1 and funty 1.2.  Without
+# this fork, bitvec 0.20.x is incompatible with funty 1.2, which we depend on,
+# and leads to a compilation error.  This can be removed once the upstream PR
+# is resolved: https://github.com/bitvecto-rs/bitvec/pull/141
+bitvec = { git = "https://github.com/ed255/bitvec.git", rev = "5cfc5fa8496c66872d21905e677120fc3e79693c" }
```
[the remark this answers is not in the document]
Comment (ed255) [reply Cargo.toml:15]: done! https://github.com/appliedzkp/zkevm-circuits/issues/163

File: bus-mapping/src/eth_types.rs (hunk 4 above)
Comment (ed255) [reply bus-mapping/src/eth_types.rs]: I've updated the PR to use `Option` rather than `CtOption` following your advice (using the `into()` that you introduced in subtle :P).  Currently this is only used in zkevm-circuits for tests and always with `unwrap()`, so both `Option` and `CtOption` compile fine.

File: bus-mapping/src/circuit_input_builder.rs (hunk 2 above)
Comment (ed255) [reply bus-mapping/src/circuit_input_builder.rs]: Thanks for the suggestion.  I moved all the mock generation functions and types to a new module called `mock`.  Not it looks more organized.  I haven't set that module under `#[cfg(test)]` because some of the mock functions are used by the `zkevm-circuits` crate!

File: bus-mapping/src/eth_types.rs (hunk 10 above)
Comment (ed255) [reply bus-mapping/src/eth_types.rs:217]: done https://github.com/appliedzkp/zkevm-circuits/issues/164

File: bus-mapping/src/external_tracer.rs (hunk 18 above)
Comment (ed255) [reply bus-mapping/src/external_tracer.rs]: done https://github.com/appliedzkp/zkevm-circuits/issues/165

File: bus-mapping/src/external_tracer.rs (hunk 19 above)
Comment (ed255) [reply bus-mapping/src/external_tracer.rs]: done https://github.com/appliedzkp/zkevm-circuits/issues/165

File: bus-mapping/src/circuit_input_builder.rs (hunk 2 above)
Comment (CPerezz) [reply bus-mapping/src/circuit_input_builder.rs]: Seems much better! 

I'd file an issue and discuss in the next meeting or something similar what should we do with the `MockProver`, `MockTransaction` and and the testing facilities in general. :)

**Review by CPerezz — APPROVED** [review]
LGTM!!!

**Review by han0110 — APPROVED** [review]
LGTM! Nice job!
